.PHONY: help install ingest dbt-run dbt-test dbt-clean orchestrate charts text2sql format lint lint-fix check-all run-all

help install ingest dbt-run dbt-test dbt-clean orchestrate charts text2sql format lint lint-fix check-all run-all:
	@$(MAKE) -C .. $@
