a_simple_t2s_flow:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', 'duckdb_warehouse/warehouse.duckdb') }}"
      threads: 1
      schema: main
      extensions: []
